### ISSUE TITLE
Please clarify difference(s) in implementation

### ISSUE THREAD

**Issue by tuddman** [colavitam/curl-collisions#2]
I see that your implementation (in c) differs from that found [here](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/hash/Curl.java) 

Am I correct in my reading that you have shown _your_ implementation of the curl function(s) to be vulnerable.  *Not* the implementation referenced above.

**Comment by colavitam** [comment]
@tuddman, that is incorrect. These are vulnerabilities in the hash function itself, not the specific code. You will find that our implementation implements the hash function as defined by the source you provided.

**Comment by tuddman** [comment]
I didn't see where you'd implemented `pairTransform` defined [here](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/hash/Curl.java#L130)
